# Generated by Django 4.2.5 on 2023-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedinjob',
            name='date_we_got_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
