# Generated by Django 4.2.5 on 2023-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_linedinjob_date_we_got_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedinjob',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='company_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='found_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='headquarter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='industries',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='job_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='job_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linedinjob',
            name='posted_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
