# Generated by Django 4.2.5 on 2023-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_linedinjob_city_alter_linedinjob_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
