# Generated by Django 4.1.7 on 2023-09-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_numberofjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500, null=True)),
                ('api', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
