# Generated by Django 4.2.5 on 2023-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedinjob',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
