# Generated by Django 4.2.5 on 2023-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_linedinjob_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedinjob',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
