# Generated by Django 4.2.5 on 2023-09-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_linedinjob_number_of_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinedInJob',
            new_name='LinkedInJob',
        ),
    ]
