# Generated by Django 4.1.7 on 2023-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_rename_linedinjob_linkedinjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinjob',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
